### ISSUE TITLE
Put finite-typelits on stackage

### ISSUE THREAD

**Issue by turion** [mniip/finite-typelits#14]
It would be great if finite-typelits could be on stackage, so other projects that depend on it (`vector-sized`, `rhine`, ...) can be reenabled there. If you're unsure how that works I'm willing to help and/or maintain.

**Comment by turion** [comment]
I just tested and it is possible to put `finite-typelits` on stackage without any modifications. I'm willing to maintain it there. Can you say whether you want this?

**Comment by mniip** [comment]
Sure, why not.
