### ISSUE TITLE
Loosen constraint from Integer to Num or Integral

### ISSUE THREAD

**Issue by hololeap** [mniip/finite-typelits#15]
Would it be reasonable to suggest that functions that functions that return an `Integer` be changed so that they return a `Num` instead? For instance, `getFinite :: Finite n -> Integer`, could have `fromIntegral` post-composed, so that it changes to `getFinite :: Num o => Finite n -> o`.

In the same vein, functions that take an `Integer` could be changed so that they take an `Integral` instead by pre-composing `toInteger`. For instance, 

    packFinite :: (KnownNat n, Integral o) => o -> Maybe (Finite n)

**Comment by mniip** [comment]
This has been largely addressed in 0.2.0.0
