### ISSUE TITLE
Could we have exponentiation of Finites?

### ISSUE THREAD

**Issue by kozross** [mniip/finite-typelits#17]
This would be really nice to have for a project I'm working on.

**Comment by kozross** [comment]
Never mind - I just realized exactly how difficult this would be to do.

**Comment by mniip** [comment]
It's not *that* complicated, I might think about it.

**Comment by mniip** [comment]
Assuming you're talking about `(Finite n -> Finite m) <-> Finite (m ^ n)`, that was added in 5cae0c8c7a3b08965b19f3d5ace398dfaa4028f6
