### ISSUE TITLE
Generic instance allows to break data abstraction

### ISSUE THREAD

**Issue by Shimuuar** [mniip/finite-typelits#5]
Generic basically allows unrestricted access to data type constructors. So following example allows us to create Finite with arbitrary content using machinery from `fixed-vector-hetero`

```
λ> import Data.Finite
λ> import qualified Data.Vector.HFixed as H
λ> instance H.HVector (Finite n)
λ> H.mk1 666 :: Finite 3
finite 666
```

`fixed-vector-hetero` is not necessary. It's just easiest if somewhat roundabout way to create instance of data type using Generic API. 

Generic is frequently used to drive serialization instances. Since it doesn't do any checking it allows attack if malicious data is decoded. It's probably better to remove such instance.

**Comment by mniip** [comment]
Paging @mstksg (in relation to #1 )

**Comment by mniip** [comment]
I think jle did require the instance for his module, hence I believe the appropriate solution would be to write out the instance myself, making `GHC.Generics.from` partial.

**Comment by Shimuuar** [comment]
Making `from` partial is not all that great either. Now you have partial function and no way to use it in total manner. Another possibility is to use modular arithmetic instead.

**Comment by mniip** [comment]
`Finite 0`?

**Comment by Shimuuar** [comment]
Add `1 <= n` to context!

**Comment by mniip** [comment]
More like, `KnownNat n => Generic (Finite n)` because it's either a V1 or an Integer

**Comment by Shimuuar** [comment]
But we don't need `KnownNat` here. We need to rule out uninhabited `Finite 0`. But question is do we really need Generic instance?

**Comment by mstksg** [comment]
Yeah I'm actually thinking that a `Generic` instance is a bad idea now.  It's not something that's meant to exist for abstract data types like `Finite` (c.f. `Map`, `Set`, `HashMap`, `Seq`, and other canonical abstract data types in Haskell) so it probably doesn't belong for `Finite`.  I'm not sure what reason originally prompted me to ask about it, but looking back, it must have been misguided :(

**Comment by mstksg** [comment]
If we consider `Finite n` as an indexed type "family" (in the dependently typed programming sense of "type family") then each `n` should yield a different abstract data type.

Having a "correct" Generic instance for an abstract data type is iffy, but, if you can make it work correctly (and not break the abstraction) then I guess it isn't exactly *harmful*.  It might be worth putting in.  It'd work and be non-partial and not break the abstraction, but -- I'm not sure if this is against the spirit of the Generic typeclass or not.

That is, it might be "legal", but not what Generic is "supposed" to be used for.

**Comment by Shimuuar** [comment]
I think about Generic as another representation of data type which could be worked with using type classes. It doesn't provide any way to limit access, incorporate smart constructors etc. In principle it's possible to hand-write instance but I think it not worth it for such simple type.

**Comment by mniip** [comment]
Perhaps it can be represented in binary e.g `Finite 10 ~ B :*: (U1 :+: (B :*: (B :*: (U1 :+: V1))))` where `B ~ U1 :+: U1`? I'm considering creating a separate package that would deal with the type-theoretical issues of Finite, e.g this instance and promoting a 'Finite n' to SomeNat with a type-level witness.

**Comment by mniip** [comment]
Generic was removed in 02afebafcb912272af1273bea308103735508e3e
