### ISSUE TITLE
`quot` isn't modular multiplicative inverse

### ISSUE THREAD

**Issue by phadej** [mniip/finite-typelits#8]
Please either document that, or re-implement `quot` (http://hackage.haskell.org/package/integer-gmp-1.0.0.1/docs/GHC-Integer-GMP-Internals.html#v:recipModInteger):

https://en.wikipedia.org/wiki/Modular_multiplicative_inverse

```
*Data.Finite> map (quot 1) [1,2,3,4] :: [Finite 5]
[finite 1,finite 0,finite 0,finite 0]
```

vs. 

```
*Data.Fin> let ns = [0,1,2,3,4] in map (quot 1) ns :: [Fin N.Nat5]
[0,1,3,2,4]
*Data.Fin> let ns = [0,1,2,3,4] in zipWith (*) ns (map (quot 1) ns) :: [Fin N.Nat5]
[0,1,1,1,1]
```

*Note:* modular inverse works well only for prime modulus.

**Comment by mniip** [comment]
I don't think it was ever intended to be used that way.
